### ISSUE TITLE
Could it be force to be a generic bean/jmx exporter?

### ISSUE THREAD

**Issue by mdone-cloudian** [instaclustr/cassandra-exporter#86]
You state right at the beginning that this exporter is faster than jmx_exporter, even when the latter is also run as an Agent. My question would be, could I hack this thing to make it export other beans in other java services and process values (heap, etc) without penalizing much its speed?

**Comment by zegelin** [comment]
Hi @mdone-cloudian. 

Are you using the exporter with Cassandra and wish that it could export something that it currently doesn't? If so, let us know and we can look into adding support for it.

Or are you asking if this exporter could be adapted to work with other JVM-based applications?
Currently the exporter is very much tailored towards exporting Cassandra metrics and certain JVM metrics. However, some of the logic is already modular, for example the mini HTTP server, exposition formatting, MBean server hooks, etc. With a bit of work it's quite possible that this could be adapted to work with other JVM apps. Is there a specific application for which you're experiencing sub-par performance with `jmx_exporter`?

**Comment by mdone-cloudian** [comment]
> Currently the exporter is very much tailored towards exporting Cassandra metrics

Do you do this by targeting specific beans, or do you scan them all like most other bean exporters around?

> are you asking if this exporter could be adapted to work with other JVM-based applications?

yes

> and certain JVM metrics

I don't see any in https://github.com/instaclustr/cassandra-exporter/wiki/Exported-Metrics

> Is there a specific application for which you're experiencing sub-par performance with jmx_exporter?

I haven't tried the other ones yet, but we also run `redis` and at least 3 in-house JVM apps.

**Comment by zegelin** [comment]
Sorry for the delayed reply.

> Do you do this by targeting specific beans, or do you scan them all like most other bean exporters around?

This exporter, when run as an agent, hooks into MBean registration by installing a `MBeanServerInterceptor` into the host JVM's `MBeanServer`. This gives us two things:

1. Access to the raw objects, rather than the proxies, as created by JMX.
2. Immediate notification of MBean registration.

See the logic in https://github.com/instaclustr/cassandra-exporter/blob/cb3e231f13448bdae59cee6a81703490feddca60/agent/src/main/java/com/zegelin/cassandra/exporter/MBeanServerInterceptorHarvester.java#L66

When a MBean is registered, it's matched against a hard-coded hand-tuned list of converters. See https://github.com/instaclustr/cassandra-exporter/blob/cb3e231f13448bdae59cee6a81703490feddca60/common/src/main/java/com/zegelin/cassandra/exporter/FactoriesSupplier.java#L531

> I haven't tried the other ones yet, but we also run `redis` and at least 3 in-house JVM apps.

Unsure of Redis. It could be possible if it uses JMX.

For in-house apps, I'd recommend using the official Prometheus Java client: https://github.com/prometheus/client_java

The main motivations behind this project are to export Cassandra's metrics to Prometheus without having to modify the Cassandra source code. There are numerous ways to achieve this, but C*'s JMX interface the most information-rich. JMX has one major downside: it's very slow. So this project exports metrics and other info that C* makes available over JMX, without using JMX.

For applications in which you control the source code, I'd recommend instrumenting them directly with the Prometheus client.
